FROM golang:1.23 AS builder
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG PLUGIN_PATH
RUN CGO_ENABLED=0 GOOS=linux go build -o /plugin ./${PLUGIN_PATH}

FROM gcr.io/distroless/static
COPY --from=builder /plugin /plugin
ENTRYPOINT ["/plugin", "serve"]
