#!/usr/bin/env bash
# Builds test plugin container images from tests/plugins/*/ and pushes them
# to the kubevirtci cluster's local registry.
set -e

source hack/config.sh
source cluster/kubevirtci.sh
kubevirtci::install

# The provider config is generated by kubevirtci during cluster-up and sets
# docker_prefix to the host-side registry address (localhost:<port>/kubevirt).
KUBEVIRTCI_CONFIG_PATH="$(kubevirtci::path)/_ci-configs"
source "${KUBEVIRTCI_CONFIG_PATH}/${KUBEVIRT_PROVIDER}/config-provider-${KUBEVIRT_PROVIDER}.sh"

# Fail early if the cluster isn't up (docker_prefix would be empty).
: ${docker_prefix:?"docker_prefix not set - is the cluster running?"}

if command -v podman &>/dev/null; then
    BUILDER="podman"
else
    BUILDER="docker"
fi

found=0
for plugin_file in tests/*/plugin.go; do
    [ -f "${plugin_file}" ] || continue
    grep -q '^package main' "${plugin_file}" || continue
    found=1
    plugin_dir=$(dirname "${plugin_file}")
    plugin_name=$(basename "${plugin_dir}")
    image="${docker_prefix}/${plugin_name}:${DOCKER_TAG}"

    echo "Building ${image}..."
    ${BUILDER} build \
        -t "${image}" \
        -f Dockerfile.test-plugin \
        --build-arg "PLUGIN_PATH=${plugin_dir}" \
        .

    # kubevirtci's local registry is HTTP-only, so TLS verification must be skipped.
    echo "Pushing ${image}..."
    ${BUILDER} push --tls-verify=false "${image}"
done

if [ "${found}" -eq 0 ]; then
    echo "No test plugins found (no tests/*/plugin.go), skipping."
    exit 0
fi

echo "Done building test plugin images."
