#!/usr/bin/env bash
# Builds test plugin container images from tests/plugins/*/ and pushes them
# to the kubevirtci cluster's local registry.
set -e

source hack/config.sh
source cluster/kubevirtci.sh
kubevirtci::install

# The provider config is generated by kubevirtci during cluster-up and sets
# docker_prefix to the host-side registry address (localhost:<port>/kubevirt).
KUBEVIRTCI_CONFIG_PATH="$(kubevirtci::path)/_ci-configs"
source "${KUBEVIRTCI_CONFIG_PATH}/${KUBEVIRT_PROVIDER}/config-provider-${KUBEVIRT_PROVIDER}.sh"

# Fail early if the cluster isn't up (docker_prefix would be empty).
: ${docker_prefix:?"docker_prefix not set - is the cluster running?"}

PLUGIN_DIR="tests/plugins"
if [ ! -d "${PLUGIN_DIR}" ]; then
    echo "No test plugins found in ${PLUGIN_DIR}, skipping."
    exit 0
fi

if command -v podman &>/dev/null; then
    BUILDER="podman"
else
    BUILDER="docker"
fi

for plugin in "${PLUGIN_DIR}"/*/; do
    [ -d "${plugin}" ] || continue
    plugin_name=$(basename "${plugin}")
    image="${docker_prefix}/${plugin_name}:${DOCKER_TAG}"

    echo "Building ${image}..."
    ${BUILDER} build \
        -t "${image}" \
        -f Dockerfile.test-plugin \
        --build-arg "PLUGIN_PATH=${plugin}" \
        .

    # kubevirtci's local registry is HTTP-only, so TLS verification must be skipped.
    echo "Pushing ${image}..."
    ${BUILDER} push --tls-verify=false "${image}"
done

echo "Done building test plugin images."
